name = "HypergraphDatasets"
uuid = "c83b4d74-e7ca-4499-8513-8f5b36e9c99e"
authors = ["Evan Spotte-Smith <espottesmith@gmail.com>"]
version = "0.0.1-DEV"

[deps]
HyperGraphNeuralNetworks = "1aebdcae-dc77-44ee-b348-f058d326ae63"

[compat]
HyperGraphNeuralNetworks = "0.0.1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
